### ISSUE TITLE
شخصی سازی اعداد و مکلمات

### ISSUE THREAD

**Issue by AliEasy** [gabrimatic/persian_datetimepickers#1]
با سلام
اگر یک فونت و رنگ و کلا استایل تکست هارو شخصی سازی کنیم عالی میشه
برای دکمه ها و  عنوان دیالوگ و اعداد و در کل همه چی
تشکر

**Comment by salehzarei** [comment]
من هم همین تقاضا رو دارم ، تغییر فونت و ایجاد محدودیت در بازه زمانی

**Comment by gabrimatic** [comment]
All changes applied to the new version [1.0.3]. Now I close the issue.
